version: "3"

services:
  analyze_frontend:
    build:
      context: ../../
      dockerfile: DEVELOPMENT_Dockerfile
    ports:
      - "9000:80"
    volumes:
      - "../../pages:/app/pages"
      - "../../elm.json:/app/elm.json"
      - "../../package.json:/app/package.json"
      - "../../compiler:/app/compiler"
    container_name: analyze_frontend_dev
    command: sh /start_dev_watcher.sh

