version: "3"

networks:
  analyze:
    external: false

services:
  analyze_api:
    image: bmff/analyze-api
    environment:
      - POSTGRES_URL=postgres://test:test@analyze_db:5432/test?sslmode=disable
      - ALLOWED_URL=https://maximilianehlers.com/analyze
    ports:
      - "8080:10920"
    depends_on:
      - analyze_db
    networks:
      - analyze
    restart: always
  analyze_db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - analyze
    restart: always
  analyze_frontend:
    image: bmff/analyze-frontend
    ports:
      - "80:80"
    restart: always
