version: "3"

networks:
  analyze_dev:
    external: false

services:
  analyze_api:
    build:
      context: .
      dockerfile: ./DEV_DOCKERFILE
      args:
        - USER
    environment:
      - POSTGRES_URL=postgres://test:test@analyze_devdb:5432/test?sslmode=disable
      - USER
      - ALLOWED_URL=*
    ports:
      - "8080:10920"
    depends_on:
      - analyze_db
    networks:
      - analyze_dev
    volumes:
      - "../..:/go/src/api"
    container_name: analyze_dev
  analyze_db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - analyze_dev
    container_name: analyze_devdb
